security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: 'foo'
                        roles: 'ROLE_ADMIN'

    password_hashers:
        Symfony\Component\Security\Core\User\InMemoryUser: 'plaintext'

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
                default_target_path: /admin
            logout:
                path: logout
                target: /
            provider: in_memory
            lazy: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
